MF:
  lr: 0.0001
  net:
    W_0_hidden: 0
    f_act: leakyrelu
    f_num_hid_layers: 4
    f_num_hidden: 128
    g_act: leakyrelu
    g_num_hid_layers: 4
    g_num_hidden: 128
    grad_sigma: false
    label_f: false
    label_g: false
    label_x: 0
    label_y: 0
    num_cond_inputs: 1
    num_inputs: 2
    sigma: 1
MLP: null
NF:
  lr: 0.0001
  net:
    num_cond_inputs: 1
    num_hidden: 32
    num_inputs: 2
    s_act: tanh
    t_act: relu
  num_blocks: 1
dataset:
  fcn_Ku: '[abs(X - xi)-abs(xi - X), abs(Y - yi) - abs(yi - Y)]'
  fcn_h: '[-xi, -yi]'
  fcn_sigma: '1'
  fore_range: 0.2
  irregular: false
  k: 2
  n_jumps: 4
  n_particles: 100
  n_points: 100
  simulation: true
  t0: 0
  tn: 5
head: OU_jump
loader:
  batch_size_paths: 20
  batch_size_points: 512
n_runs: 10
n_tries: 1
optimizer:
  n_epochs: 500
  name: AdamW
other:
  loss_type: girsanov
  test_n_particles: 100
  test_y_samp_size: 128
  train_y_samp_size: 128
