MF: null
MLP:
  lr: 0.001
  net:
    act: leakyrelu
    num_cond_inputs: 1
    num_hid_layers: 10
    num_hidden: 64
    num_inputs: 1
    num_outputs: 1
    sigma: 3
NF: null
dataset:
  dataset_type: co2a0000396/co2a0000396.rd.112
  path: /global/path/data/EEG/
  scale_t: 1
  seed: 3
  simulation: false
  split_size: 0.8-0.1-0.1-0.8
  split_type: both
  subset_time: null
deepAR: null
head: EEG
loader:
  batch_size_paths: 5
  batch_size_points: 1024
n_runs: 5
n_tries: 1
optimizer:
  n_epochs: 500
  name: AdamW
other:
  loss_type: gaussian
  test_n_particles: 100
  test_y_samp_size: 128
  train_y_samp_size: 128
transformer: null
