MF:
  lr: 0.001
  net:
    W_0_hidden: 128
    f_act: tanh
    f_num_hid_layers: 2
    f_num_hidden: 64
    g_act: tanh
    g_num_hid_layers: 2
    g_num_hidden: 64
    grad_sigma: false
    label_f: false
    label_g: false
    label_x: 0
    label_y: 0
    num_cond_inputs: 1
    num_inputs: 2
    sigma: 1
MLP: null
NF: null
dataset:
  T: 0.1
  datatype: pinwheel
  generative: true
  n_bridge: 1
  n_points: 25
  n_samples: 200
  simulation: true
head: pinwheel
loader:
  batch_size_paths: 20
  batch_size_points: 512
n_runs: 10
n_tries: 1
optimizer:
  n_epochs: 200
  name: AdamW
other:
  loss_type: girsanov
  test_n_particles: 200
  test_y_samp_size: 128
  train_y_samp_size: 128
