dataset:
  dataset_type: power_data.npy
  path: /global/path/data/realGen/
head: power
loader:
  batch_size: 200
model: vae
n_epochs: 100
n_runs: 10
n_tries: 1
vae:
  latent_dim: 50
  lr: 0.0001
  num_hidden: 128
