MF: null
MLP: null
NF: null
dataset:
  dataset_type: V_0208
  path: /global/path/data/chemotaxi/
  scale_t: 1
  simulation: false
  split_size: 0.8-0.1-0.1-0.8
  split_type: both
  subset_time: null
deepAR: null
head: Chemotaxi
loader:
  batch_size_paths: 10
  batch_size_points: 1024
n_runs: 5
n_tries: 1
optimizer:
  n_epochs: 500
  name: AdamW
other:
  loss_type: gaussian
  test_n_particles: 100
  test_y_samp_size: 128
  train_y_samp_size: 128
transformer:
  lr: 0.001
  net:
    nhid: 256
    ninp: 3
    nlayers: 4
  window_size: 10
